[build-system]
requires=['setuptools', 'setuptools-scm']
build-backend='setuptools.build_meta'

[project]
name='django-cml2'
version='1.0.0'
description='My package description'
readme='README.rst'
license={text="BSD-3-Clause"}

authors=[
    {name='Sergey Grunenko', email='grunenko.serg@gmail.com'},
]

requires-python='>=3.3.0'
dependencies=[
    'Django>=3.2',
    'django-appconf>=1.0.1',

    'importlib-metadata; python_version<"3.8"',
]
#dynamic=['version']

keywords=['cml', 'Commerce ML 2']
classifiers=[
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Django :: 3.2',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
]

[project.urls]
#homepage='https://example.com'
documentation='https://readthedocs.org'
#repository='https://github.com/sergey-gru/django-cml2'
#changelog='https://github.com/me/spam/blob/master/CHANGELOG.md'

[project.scripts]
my-script='my_package.module:function'
