# Generated by Django 3.2.18 on 2023-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cml', '0002_reorganize_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='operation',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='file_name',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
